name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout code
        run: ls -a
      - name: download
        run: curl -O https://www.digitalocean.com/robots/txt
      - name: cat
        run: cat robots.txt

  
    
