name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: See files
        run: ls -a
      - name: download robots.txt
        run: curl https://www.digitalocean.com/robots.txt --output robots.txt
      - name: read robots.txt
        run: cat robots.txt

  
    
